// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckLog struct {
	ID         int32            `json:"id"`
	MonitorID  pgtype.Int4      `json:"monitor_id"`
	StatusCode pgtype.Int4      `json:"status_code"`
	Success    pgtype.Bool      `json:"success"`
	CheckedAt  pgtype.Timestamp `json:"checked_at"`
}

type Monitor struct {
	ID              int32            `json:"id"`
	UserID          pgtype.Int4      `json:"user_id"`
	Url             string           `json:"url"`
	Method          pgtype.Text      `json:"method"`
	IntervalSeconds int32            `json:"interval_seconds"`
	Status          pgtype.Text      `json:"status"`
	LastChecked     pgtype.Timestamp `json:"last_checked"`
}

type User struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
